import 'dotenv/config'

export const env = {
	MONGODB_URI: process.env.MONGODB_URI,
	DB_NAME: process.env.DB_NAME,
	LOCAL_DEV_HOST: process.env.LOCAL_DEV_HOST,
	LOCAL_DEV_PORT: process.env.LOCAL_DEV_PORT,
	LOCAL_DEV_FORNTEND_PORT: process.env.LOCAL_DEV_FORNTEND_PORT,

	CLOUD_NAME: process.env.CLOUD_NAME,
	API_KEY_CLOUDINARY: process.env.API_KEY_CLOUDINARY,
	API_SECRET_CLOUDINARY: process.env.API_SECRET_CLOUDINARY,

	ACCESS_TOKEN_SECRET_SIGNATURE: process.env.ACCESS_TOKEN_SECRET_SIGNATURE,
	REFRESH_TOKEN_SECRET_SIGNATURE: process.env.REFRESH_TOKEN_SECRET_SIGNATURE,
	BUILD_MODE: process.env.BUILD_MODE,

	AUTHOR: process.env.AUTHOR,
	APP_PASSWORK: process.env.APP_PASSWORK,
	EMAIL: process.env.EMAIL,
	ORDER_TOKEN_SECRET_SIGNATURE: process.env.ORDER_TOKEN_SECRET_SIGNATURE,
	EMAIL_SELL: process.env.EMAIL_SELL


}